### ISSUE TITLE
G19 - High School Code Change

### ISSUE THREAD

**Issue by JoyLindsay** [dsu-effectiveness/usheUtils#94]
Blank **g_high_school** needs to be coded as **459200** for unknown.

g_high_school **459997** needs to be changed/coded as **459100**.

**Comment by cyberLaVoy** [comment]
This should be resolved with latest update.

**Comment by JoyLindsay** [comment]
g_high_school 459997 is still showing up. It needs to be coded as 459100.

**Comment by CraigDemke** [comment]
Should be good now.

**Comment by JoyLindsay** [comment]
This is clear, ready to close.
